### PR TITLE
Update Babel, Traceur, CoffeeScript, and CodeMirror

### PR DESCRIPTION
**Pull request by arkon**
I couldn't get the latest version of LiveScript working, so I'll leave that for another PR.

### CODE REVIEW

**Comment by richgilbank** [comment]
:+1: thanks!

**Comment by richgilbank** [comment]
I hadn't yet updated the Chrome package, but it seems master wasn't fully working for the last few days...this removed the browser polyfill which is still needed for some features like generators. I believe things should be working again though as of https://github.com/richgilbank/Scratch-JS/commit/73b692c5c519f818c79183b1aa6af902b55abf97. @arkon, mind double checking I didn't miss anything there?

**Comment by arkon** [comment]
@richgilbank I think there might still be an issue since the babel-core dependency was replaced with babel-standalone... might need to look into this more.

**Comment by richgilbank** [comment]
Took me a while to get to it (understatement!) but [this commit](https://github.com/richgilbank/Scratch-JS/commit/b73630fbefb6faa44f0444b4db60e06764aca9f9) seems to work.

**Pull request merged**
